name: Camelot
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        repository: LineageOS/android_packages_apps_Camelot
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: "21"
        distribution: "temurin"
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - uses: softprops/action-gh-release@v2
      if: github.event_name != 'pull_request'
      with:
        name: Camelot
        tag_name: continuous.camelot
        prerelease: true
        files: app/build/outputs/apk/debug/app-debug.apk
